### ISSUE TITLE
The "évènement page link" URL is not displayed on Event Details page.

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#114]
For example see: 
* [admin tool](http://footlight-calendar-frontend.herokuapp.com/admin/add-event/?id=62e2ace70b066d0070c62100)
* [front-end calendar](http://footlight-calendar-frontend.herokuapp.com/events/real-beland-et-didier-lucien-la-nature-comique/62e2ace70b066d0070c62100?lang=fr&date=2022-08-17_16-00-37)

**Comment by SuhailAliyar** [comment]
@saumier @troughc 
Do you suggest a location to display the "évènement page link"?

In **https://toutculture.ca/** the event link is displayed along with the contact. 
eg: https://toutculture.ca/evenements/real-beland-et-didier-lucien-la-nature-comique-2/21013?date=2022-08-17_16-00-00

Do we display the link below a new subheading "évènement link"?

**Comment by troughc** [comment]
My thought is that we could display this as a More Info (En Savoir Plus) button, but would like to discuss with our UX/UI designer 
 @saumier what do you think?

**Comment by saumier** [comment]
@troughc A button is a good idea, but this issue is already done as a link on the event details page left column. So I am going to close it.
