### ISSUE TITLE
Youtube Video-url

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#116]
As an admin, I can copy/paste a youtube or vimeo url into the video field of an event.

The front-end displays the youtube or vimeo video in a dedicated place below the event's description.
Example:
https://toutculture.ca/evenements/lundis-musicaux/20809?date=2022-08-29_18-30-00

**Comment by SuhailAliyar** [comment]
@SuhailAliyar To generate Gravatar URL from backend and the URl will be loaded in UI.

**Comment by saumier** [comment]
@raseemayatt Please change the label in the admin tool to be "Video URL" and enable both Youtube and Vimeo videos to play in the admin tool.

Here is an example Vimeo URL: `https://vimeo.com/633172534`

If this helps, here is the embed code: 
```
<iframe src="https://player.vimeo.com/video/633172534?h=eda036ee8b&color=ffffff&portrait=0&badge=0" width="640" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
<p><a href="https://vimeo.com/633172534">Ghosts</a> from <a href="https://vimeo.com/eps696">Vadim Epstein</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
```

**Comment by SuhailAliyar** [comment]
Assigning to @saumier for review.

**Comment by saumier** [comment]
@troughc Please test.

**Comment by troughc** [comment]
tested and passed
