### ISSUE TITLE
Add time to all events option in Customize dialog overwrites all times instead of adding an additional time.

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#117]
steps to reproduce:
1. create weekly recurring event that has 2 times. Add one time.
2. open customize dialog to add a second time to first date. 
3. click + Add time and select time
4. enable add to all dates and click Add button.
5. Time overwrites 1st time.

Workaround
1. do steps 1-3
2. Click the Add button but do NOT enable add to all times. time is added to one date.
3. duplicate this date to all dates.

**Comment by troughc** [comment]
Tested on Safari - PASSED
Tested on CHROME - PASSED
