### ISSUE TITLE
Split Front-end Calendar from Admin tool

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#118]
* Split code into different Github repositories
     1. footlight-calendar-app repo for the front-end calendar 
     2. footlight-admin repo for the admin tool  
* Add additional Heroku app
  1. footlight-calendar-app-staging, footlight-calendar-app-production
  2. footlight-admin-staging, footlight-admin-production

**Comment by SuhailAliyar** [comment]
@raseemayatt Can you please take up the first part of this issue?

**Comment by SuhailAliyar** [comment]
Deployed both applications in Heroku.
The production apps are not deployed, since we are not using them now.

**Comment by SuhailAliyar** [comment]
@raseemayatt Can you please remove the admin section from the footlight-app code?
