### ISSUE TITLE
Event duration display (UI design)

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#12]

**Comment by troughc** [comment]
@saumier just noting here that I took an image of where duration could appear. Adding it here for reference (also added to #10  :
<img width="484" alt="Screen Shot 2022-06-07 at 11 08 33 AM" src="https://user-images.githubusercontent.com/64489312/172418349-b7b8bbad-2a93-4f1c-9a91-d07ab366573e.png">
