### ISSUE TITLE
User profile screen

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#121]
Basic user profile screen with fields and gravatar image. I am proposing the use of Gravatar because it is a sort of resuse of avatars based on your email address that can be used across systems. Basically, the gravatar is looked up using the gravatar API and an email address.

![Image](https://user-images.githubusercontent.com/419491/183299081-924467c2-e879-4f72-9963-9033791ad98b.png)

![Image](https://user-images.githubusercontent.com/419491/183299087-8905a8ca-fab6-4bc7-9831-ba1ba3dcd3f6.png)

**Comment by SuhailAliyar** [comment]
As per the discussion with @saumier, all the users will be considered as Admin for this iteration.

**Comment by saumier** [comment]
@SuhailAliyar 
 Here is an example of a default image passed to gravatar. If the email hash does not exist then it will use the url for the default image. The default image is using another web service to generate an image with initials of the name passed in.
Gravatar with existing account: https://www.gravatar.com/avatar/1ff7d7f658b5be1ad51127c61e302da2?d=https%3A%2F%2Fui-avatars.com%2Fapi%2FGregory%2BFinch
Gravatar with no account: https://www.gravatar.com/avatar/111?d=https%3A%2F%2Fui-avatars.com%2Fapi%2FGregory%2BFinch


The default image is always passed since you don’t know if the Gravatar account exists. https://ui-avatars.com/api/Gregory+Finch

**Comment by SuhailAliyar** [comment]
Assigning to @saumier for review.

**Comment by saumier** [comment]
@troughc I sent you an invite to join Footlight (users must be invited now and your previous account was deleted). Please test and also test with a gravatar.com avatar if you don't already have one. I'd like your feedback on Gravatar.

**Comment by saumier** [comment]
@troughc To add an image (Gravatar) instead of seeing your initials, you can go to gravatar.com, create an account, and upload your image. Then your image (Gravatar) will appear on websites that support Gravatar such as Footlight console and Footlight calendar. Gravatar.com is a system to create your image once and reuse it in many places.   But as per our conversation with Isabelle and Maude, we don't want to force people to create a Gravatar because that would add friction. So if you have ideas on what text to add to the UI to indicate that the Gravatar is optional, but available, please share.  I am closing this issue.

**Comment by troughc** [comment]
@saumier when I went to gravatar, I was asked to log in using Wordpress - which I did. I then was able to add a second account (Caitlin@culturecreates.com (my main Wordpress account is my gmail).  Other than that, it worked as described. I now have a gravatar image in footlight
