### ISSUE TITLE
Start time display is sometimes off by 4 hrs

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#124]
Sometimes new events have the correct time in the admin tool, but display 4 hrs off in the front-end.  

This event is set to 20h in the admin tool but displays 4pm in the front-end 
Example: http://footlight-calendar-frontend.herokuapp.com/events/dominique-fils-aime/62e28a6cbdbca9007082e6aa?lang=fr&date=2022-09-08_16-00-36 

Same event in admin:
http://footlight-calendar-frontend.herokuapp.com/admin/add-event/?id=62e28a6cbdbca9007082e6aa

Note that the front-end event details displays the correct time in the “autres dates” drop down. This event “Véronic DiCaire” is at 8pm but displays 4pm in the event details and 8pm in the “autres dates”.   

![Image](https://user-images.githubusercontent.com/419491/181908996-49ece5bd-be98-42fd-ae8b-ddf342934893.png)

**Comment by SuhailAliyar** [comment]
Could reproduce this issue. It looks like an intermittent issue. 
I suggest keeping the issue OPEN and seeing if this pop up later.

@saumier Suggest the next step with this issue.

**Comment by saumier** [comment]
@SuhailAliyar I will ask @troughc to try to add reproduction steps here.

**Comment by troughc** [comment]
@saumier @SuhailAliyar the event that I noticed it in is: http://footlight-calendar-frontend.herokuapp.com/events/womansplaining-show/62e28660bdbca9007082e4d9?lang=fr&date=2022-08-11_16-00-20
So I went in to look at this event today. Originally the time was set to 20h (last week).  
Here is what I found:
**Image from Admin**

![Image](https://user-images.githubusercontent.com/64489312/182895554-44614509-d562-4049-b3a0-aded686b24de.png)

**Image from frontend**

![Image](https://user-images.githubusercontent.com/64489312/182895589-8de469b0-bf8b-46c6-893f-0948d7c4a2e1.png)

The times match at 4PM.
Here is my test on this event.
**Steps to reproduce (SAFARI):**

1. Edit the event in the Admin too. Change the time to 20h and click Update. Time looks good
2. Go to front end and check time. Still says 4PM.
3. Check the Admin tool again - time still shows 20h (8PM) in Admin tool.

![Image](https://user-images.githubusercontent.com/64489312/182896737-2ce9e59f-48af-4430-9576-a6bc665294ba.png)

**Comment by saumier** [comment]
@SuhailAliyar Caitlin has found a new bug.  See her repro steps above.

The issue is that the URL is driving the display of the event date/time.  The above repro steps work because the same URL for the event details is being used.  If you return to the listing and then come back to the event details (with a new URL) then the problem goes away.

So the URL should not determine the event's date/time. For example, if someone has a URL bookmarked, and the time changes, then selecting the bookmarked URL should not display an event at the wrong time.  The expected behaviour is that the URL select valid event date/times. If the URL has a date/time that no longer exists, or the URL has no date parameter, then the event details should ignore the date= param and display the next valid upcoming date/time.   

The following tests are quick ways to reproduce the bug:
Test 1: Change the event details URL param &date= to have a date/time that does not exist for the event.
Test 2: Remove the &date= param completely
Test 3: Change the event details URL param &date= to have an invalid date/time (example: &date=2044 and 2022-99-99)

**Comment by saumier** [comment]
@raseemayatt Getting closer, but still an issue.  When the URL date/time does not match an existing date/time then it should  display the next valid upcoming date/time.
