### ISSUE TITLE
Supply Event Status display (UI design)

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#13]

**Comment by saumier** [comment]
@troughc Can you do a first pass at the UI screen design?

**Comment by saumier** [comment]
@troughc Can you do a first pass at the UI screen design?

**Comment by troughc** [comment]
@saumier I shared the keynote detailing UI for event status. this keynote also includes a change to how to display dates on vignettes (slide 1). Link: https://www.icloud.com/keynote/026tAWpQJBsiRf94pa85Rj30g#tout_culture_-_Display_updates_-_caitlin
