### ISSUE TITLE
multiple times not in right order in custom dialog

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-calendar-app#130]
steps to reproduce (CHROME):

1. create weekly recurring event with multiple dates. Add a time. For example 20h
2. open customize dialog to add a second time to first date that is earlier than time that is already there. Click + Add time and select time. For example 18h
4. Dnable add to all dates and click Add button.
5. Times are in the wrong order. 20h is before 18h
6. Click Done. in the main Add event page 20h is still listed before 18h.

**Comment by troughc** [comment]
@saumier sorry I put this in the wrong repository - should be in Footlight admin I think

**Comment by saumier** [comment]
The date/time are still not ordered correctly in the front-end calendar

![Image](https://user-images.githubusercontent.com/419491/183777416-c652e5cc-7d91-478b-8f90-0de65004107c.png)

**Comment by saumier** [comment]
![Image](https://user-images.githubusercontent.com/419491/183916068-f9a073d6-9993-4b1c-af84-d1829fa7c2b8.png)

**Comment by SuhailAliyar** [comment]
Identified and fixed the issues reported above in the admin app. However, the reported issue in the calendar app could not be reproduced.

If the issue is persisting, can we have a working session and reproduce the issue.
