### ISSUE TITLE
Assign type taxonomy in event create/edit screen

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#135]
As an admin, I want to add a type to my event. I should be able to view the tree structure and open/close nodes of the tree to see subtypes. 

I also want to be able to type in a subtype like Jazz without having to expand the nodes of the tree.

**Comment by saumier** [comment]
Looking good,  but when I click Cancel, the screen goes to the list of CONTACTS. Expected behaviour is to return to the list of Taxonomies.

Same bug with Organizations. Click an organization, then click Cancel, the screen goes to list of CONTACTS.

**Comment by SuhailAliyar** [comment]
Assigning to @saumier for review.
