### ISSUE TITLE
Event crash

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#137]
This event crashes the system. 
http://footlight-admin-staging.herokuapp.com/admin/add-event/?id=62e27077bdbca9007082dc4e
I was playing around with dates. Please explore why and prevent the crash.

**Comment by SuhailAliyar** [comment]
Can you please explain the steps to reproduce the issue?

**Comment by saumier** [comment]
Yesterday I could reproduce just by clicking the link and the event would only display a blank screen. Today I cannot reproduce. So I will close this issue.
