### ISSUE TITLE
Event detail page - Cendrillon/Cinderella

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#14]
Event: Cendrillon

This is a virtual online event.

In order to build this event page we need new UI components for attendance mode, dates (without time) and virtual location.  The design of these UI components should be done before starting work on building this page.

See issue#11 issue#13

![626c1a150dbc0 png](https://user-images.githubusercontent.com/419491/168086241-f18ea9b4-dd6f-480f-9cae-25636c6d8af2.jpeg)

**Comment by SuhailAliyar** [comment]
See comment attendance mode in https://github.com/culturecreates/footlight-calendar-app/issues/11

**Comment by SuhailAliyar** [comment]
As per the discussion with Gregory, 
Suhail to modify the Event listing API to provide the attendanceMode.

**Comment by SuhailAliyar** [comment]
I am done with adding attendance mode to event listing API and event detail API responses.
@raseemayatt Please note the response:
Attendance mode can be "ONLINE", "OFFLINE" or "MIXED".
Virtual Event will have attendance mode "ONLINE".
The hybrid event will have attendance mode "MIXED".


{
  "data": [
    {
      "uuid": "628f753410e66100702c2ab8",
      "name": {
        "fr": "Heure du conte en ligne : Cendrillon",
        "en": "Storytelling hour on-line: Cinderella"
      },
      "image": {
        "uri": "https://dl.airtable.com/.attachments/8ca4187e03f98569e1eee8b161b1524e/e3e6c6a2/image.jpeg?ts=1653568821&userId=usrpZITku33fiktQC&cs=c51175678e170cf9"
      },
      "locationName": {
        "fr": "Réseau BIBLIO de l'Outaouais"
      },
      "startDate": "2022-04-30T00:00:00.000Z",
      "endDate": "2022-05-31T00:00:00.000Z",
      **"attendanceMode": "ONLINE"**
    },
    {
      "uuid": "628f753410e66100702c2a93",
      "name": {
        "fr": "Rachid Badouri - Les fleurs du tapis",
        "en": "Rachid Badouri - Flowers in the carpet"
      },
      "image": {
        "uri": "https://dl.airtable.com/.attachments/7469e6668a0a628e74e2f07d6c60de09/758e346c/image.jpeg?ts=1653568821&userId=usrpZITku33fiktQC&cs=e9779fd1aa18ac29"
      },
      "locationName": {
        "fr": "Salle Odyssée (Maison de la culture de Gatineau)"
      },
      "startDate": "2022-05-10T00:00:00.000Z",
      "endDate": "2022-07-23T00:00:00.000Z",
      **"attendanceMode": "OFFLINE"**
    }
}
