### ISSUE TITLE
Calendar App - review and fix all warnings

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#142]
We will be sharing the github repository with external agencies.  The code should be optimized to reduce memory, components should be split into small single purpose components to improve reusability and a good separation of concerns, and all code and runtime warnings fixed.

**Comment by SuhailAliyar** [comment]
Assigning to @saumier for review.

**Comment by saumier** [comment]
The front end calendar still has warnings when I run on my local dev, but this is low priority so I am closing this issue. After the launch we can revisit how to make the vanilla front-end more SEO friendly with some server side rendering, and then clean up the code.
