### ISSUE TITLE
Supply header and footer

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#22]
Please reproduce the yellow header and gray footer as in this screen design.

The idea of placing the search box on-top of the yellow header image makes it part of the header. So the search box appears on all pages including the event details page as in the current Caligram implementation which we are copying.  I also change the footer to say "Powered by Footlight".

Note that I have removed all navigation in the header and footer  (Accueil | À propos | Contact etc. ) so we don't have to worry about creating other pages in this phase.

![Image](https://user-images.githubusercontent.com/419491/170053952-c1212872-6a70-4991-ba03-06f16d1966ca.png)

**Comment by saumier** [comment]
Please reproduce the yellow header and gray footer. 

The idea of placing the search box on-top of the yellow header image makes it part of the header. So the search box appears on all pages including the event details page as in the current Caligram implementation which we are copying.

Note that I have removed all navigation in the header and footer  (Accueil | À propos | Contact etc. ) so we don't have to worry about creating other pages in this phase.

![Image](https://user-images.githubusercontent.com/419491/170053952-c1212872-6a70-4991-ba03-06f16d1966ca.png)

**Comment by saumier** [comment]
@raseemayatt Here is the logo of Toutculture I grabbed from their webpage https://toutculture.ca/images/logo_header.svg

**Comment by raseemayatt** [comment]
@saumier fixed header and footer without keeping fixed search box in event detail page. To keep the search field fixed in all screen may take little more time. Is it a prioritized issue?

**Comment by saumier** [comment]
@raseemayatt Thanks. We can close this issue now. Later we can add a new issue to add the search field to the event details page.
