### ISSUE TITLE
UI: Calendar custom dates selected by drag

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#45]
A range of dates can be selected/unselected by dragging the mouse. 

Example 1: Maude selects 2 solid months (now blue) and then drags down on the Monday column to unselect all the Monday.
Example 2: Maude clicks on Monday and drags to the right to select all the days of the week.

See slide 10 speaker notes:
What if you could drag down to select the dates of one day (for example thursdays) - this would enable you to easily add a second set of days to a weekly recurring event.
Would be great to be able to select one range, then add a second range of events using a mouse/hotkey combination. This enables people to skip days they don’t want. 
Also would be interesting if you could draw a ‘box’ around dates to select. For example, select Monday to Friday for the entire month (in the screenshot above you would draw a box around May 2-6 and down to May 30 - end of that line).

**Comment by troughc** [comment]
this one is not ready to test. 
@raseemayatt @SuhailAliyar @saumier I have a question: Is it possible to use drag in different ways to select? i.e. drag to select a continuous range (for example a month) AND to drag to select or deselect a 'column' range of days (for example Mondays)? I've never seen that.

To get the ball rolling, here are some ideas on how we might implement this if it makes sense to you guys. 
 
- User enters the the 'custom recurring events' dialog clean (no dates selected).
- User selects a range of dates (for example a month) by dragging to select (for example from August 1 - August 30). All the dates are highlighted and added to the Dates section on the right side of the dialog. They can then finish setting up the event series.
- QUESTION: what if the user wants to clear their selection? What is the standard approach? In my experience, it would be to drag a new range or click on the calendar to remove. Is this different on MOBILE?

To add or remove more dates: 
- User presses a HOTKEY + drag to select / deselect a COLUMN range of dates (for example Thursdays) within/inside OR outside the original range of dates. These dates are added or removed on the right side (in the dates section).
- User presses a HOTKEY + drag to select or deselect a ROW range of dates (for example Monday to Wednesday)  within OR outside the original range of dates (SHIFT+drag?). These dates are added or removed on the right side.
- User presses a HOTEKEY + drag to add another continuous range of dates outside of the original range of dates (for example September 15 to September 30) 
- User wants to add or remove ONLY ONE date. Is a hot key required for logical reasons? I think so.

We need to think about whether we need one or more hotkeys to make this work. Can we reuse the same hotkey for different types of action?

To help the user avoid making mistakes that could waste their time: When dates are removed using the calendar on the left, it works the same as using the TRASH icon: in the Dates section on the right, the dates are 'deleted' but the action can be undone as long as you are in session (unless you click the trash icon one more time).

**Comment by troughc** [comment]
SAFARI: This is not workingI. When I select a range of dates (SAFARI), the following happens - I see invalid dates: 

![Image](https://user-images.githubusercontent.com/64489312/177196035-b42d8304-0e71-47e8-b602-880d1e1cf945.png)

I cannot seem to save the event (maybe my computer)?
I tried this more than once: 
first time I added custom dates to a new event without a title
Second time I added custom dates to event with a title.
Neither time worked.

CHROME: Working better than SAFARI but a couple issues:
steps
1. Click Add an event
2. Create a title
3. click Recurring event and select Custom.  Custom recurring event dialog appears.
4. drag to select a range. range is highlighted in calendar and appears on the right in dates section.
5. drag another range - range is added
6. click individual dates - added
7. click one date inside the range - deleted on the right but not in the calendar (date is still highlighted)
PROBLEM - DATE STILL HIGHLIGHTED IN THE CALENDAR ON LEFT AFTER BEING DELETED:
![Image](https://user-images.githubusercontent.com/64489312/177197505-91af16e9-1117-4561-95c8-75383bfdde09.png)
8. Tried to DRAG to deselect a range - this does nothing.
9. I cannot drag to select columns. 
I'm going to add my previous comment back in for ideas on how to handle adding and/or removing 'column' ranges (for example a series of Thursdays.

**Comment by troughc** [comment]
Comment on how to deal with add or removing a column range etc - for discussion:
@raseemayatt @SuhailAliyar @saumier I have a question: Is it possible to use drag in different ways to select? i.e. drag to select a continuous range (for example a month) AND to drag to select or deselect a 'column' range of days (for example Mondays)? I'm curious as I've never seen this implemented on desktop.

Here are some ideas on how we might implement this using an additional hotkey if it makes sense to you guys. 
 
User enters the the 'custom recurring events' dialog clean (no dates selected) and wants to select a range of dates
- User drags to select a continuous range of dates (for example from August 1 - August 30). All the dates are highlighted and added to the Dates section on the right side of the dialog. User can then finish setting up the event series.
QUESTION 1: what if the user wants to clear their selection? What is the standard approach? In my experience, it would be to drag a new range or click on the calendar to remove.
QUESTION 2: Is this different on MOBILE? is it more gestural on mobile?

To add or remove more dates: 
- right now the user can simply click more dates or drag more dates to add another range. Is this the best way? Does it enable refined control? Can this be done gesturally? Or do we need to use a hotkey-mouse combination? For example:
- User presses a HOTKEY + drag to select / deselect a COLUMN range of dates (for example Thursdays) within/inside OR outside the original range of dates. These dates are added (if outside original range) or removed (if inside range). They are displayed on the right side (in the dates section).
- User presses a HOTKEY + drag to select or deselect a ROW range of dates (for example Monday to Wednesday)  within OR outside the original range of dates (SHIFT+drag?). These dates are added (if outside range) or removed (if inside the range); and displayed on the right side in Dates section.
- User presses a HOTEKEY + drag to add another continuous range of dates outside of the original range of dates (for example September 15 to September 30). - Added and displayed.
- User wants to add or remove ONLY ONE date. Is a hot key required for logical reasons? I think so. I also think we need to be able to deselect a range (see QUESTION above)

Do we need one or more hotkeys to make this work? If so, can we reuse the same hotkey for different types of actions?

ALREADY IMPLEMENTED: To help the user avoid making mistakes that could waste their time: When dates are removed using the calendar on the left, it works the same as using the TRASH icon: in the Dates section on the right, the dates are 'deleted' but the action can be undone as long as you are in session 
NOTES: 
1. these dates should also be removed from the calendar on the left. 
2. These dates should be permanently removed when you save or update the event. The next time you open the event, the dates are gone.
3. User should be able to click the trash icon an additional time to complete the deletion and remove the dates from the list permanently (while in session).

**Comment by SuhailAliyar** [comment]
@troughc Can we move this issue to Done?

**Comment by troughc** [comment]
@saumier I am moving this issue to done, but I haven't yet closed it.  Before I do so, can we discuss my comments from earlier in this thread (copied below): 

> Comment on how to deal with add or removing a column range etc - for discussion: @raseemayatt @SuhailAliyar @saumier I have a question: Is it possible to use drag in different ways to select? i.e. drag to select a continuous range (for example a month) AND to drag to select or deselect a 'column' range of days (for example Mondays)? I'm curious as I've never seen this implemented on desktop.
> 
> Here are some ideas on how we might implement this using an additional hotkey if it makes sense to you guys.
> 
> User enters the the 'custom recurring events' dialog clean (no dates selected) and wants to select a range of dates
> 
> * User drags to select a continuous range of dates (for example from August 1 - August 30). All the dates are highlighted and added to the Dates section on the right side of the dialog. User can then finish setting up the event series.
>   QUESTION 1: what if the user wants to clear their selection? What is the standard approach? In my experience, it would be to drag a new range or click on the calendar to remove.
>   QUESTION 2: Is this different on MOBILE? is it more gestural on mobile?
> 
> To add or remove more dates:
> 
> * right now the user can simply click more dates or drag more dates to add another range. Is this the best way? Does it enable refined control? Can this be done gesturally? Or do we need to use a hotkey-mouse combination? For example:
> * User presses a HOTKEY + drag to select / deselect a COLUMN range of dates (for example Thursdays) within/inside OR outside the original range of dates. These dates are added (if outside original range) or removed (if inside range). They are displayed on the right side (in the dates section).
> * User presses a HOTKEY + drag to select or deselect a ROW range of dates (for example Monday to Wednesday)  within OR outside the original range of dates (SHIFT+drag?). These dates are added (if outside range) or removed (if inside the range); and displayed on the right side in Dates section.
> * User presses a HOTEKEY + drag to add another continuous range of dates outside of the original range of dates (for example September 15 to September 30). - Added and displayed.
> * User wants to add or remove ONLY ONE date. Is a hot key required for logical reasons? I think so. I also think we need to be able to deselect a range (see QUESTION above)
> 
> Do we need one or more hotkeys to make this work? If so, can we reuse the same hotkey for different types of actions?
> 
> ALREADY IMPLEMENTED: To help the user avoid making mistakes that could waste their time: When dates are removed using the calendar on the left, it works the same as using the TRASH icon: in the Dates section on the right, the dates are 'deleted' but the action can be undone as long as you are in session NOTES:
> 
> 1. these dates should also be removed from the calendar on the left.
> 2. These dates should be permanently removed when you save or update the event. The next time you open the event, the dates are gone.
> 3. User should be able to click the trash icon an additional time to complete the deletion and remove the dates from the list permanently (while in session).

**Comment by saumier** [comment]
Moved to Story Map for consolidation 
https://miro.com/app/board/o9J_l1cSUdI=/?moveToWidget=3458764530339372219&cot=14
