### ISSUE TITLE
UI: Recurring events - custom

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#46]
See https://github.com/culturecreates/footlight-calendar-api/issues/88

**Comment by troughc** [comment]
@SuhailAliyar I don't know what to do with this one to test it? Please provide guidance on what you are looking for.

**Comment by SuhailAliyar** [comment]
@Catlin, This issue was created to handle  UI changes in 'Recurring events - custom'. We can close this issue after closing https://github.com/culturecreates/footlight-calendar-api/issues/88.
