### ISSUE TITLE
UI: Recurring events - copy times

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#47]
https://github.com/culturecreates/footlight-calendar-api/issues/91

**Comment by SuhailAliyar** [comment]
Assigning to @troughc  fro review

**Comment by troughc** [comment]
If I understand this issue, I am testing the copying times in custom recurring event dialog. (in CHROME)
Tested on different events including the "testing custom from daily - chrome" event
http://footlight-calendar-frontend.herokuapp.com/events/62c33a17935c09007069c94a
TEST PASSED
