### ISSUE TITLE
UI: Add Contact

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#56]
See slide 24 of wireframes

This is a replica of Caligram Admin.  The form is opened by clicking the contact button.  When the form is completed all the info should be displayed in the admin tool and becomes editable.

![Image](https://user-images.githubusercontent.com/419491/175303364-71548670-b25e-4211-9373-7ab8eeae025b.png)

**Comment by SuhailAliyar** [comment]
Assigning to @troughc for review.

**Comment by troughc** [comment]
Test found following issues
- URL can be anything. You need to apply a standard approach globally to all URLs to be consistent. For example, any field that takes a URL must have text that fits the expected URL format (like starts with http(s)://)
- All fields are required - in my opinion, this shouldn't be the case.  For now, I would say only Name and a URL should be required. @saumier do you have an opinion?
- When I press Enter on the keyboard after typing in any field, the tool thinks I want to Save the contact. This is NOT what I want. When working in a text field, pressing Enter simply means I'm done in the field. Please apply this standard approach globally. So:
How it works:
1. Click in a field (for example Nom)
2. type a name (for example Roger Roger)
3. Hit Enter. All the empty fields are highlighted as requiring info and the cursor remains in the field. So I have to use my mouse to move the cursor.
4. I keep doing this until the last field. If I hit enter after typing in the last required field, the new contact is saved and closed automatically.

How I think it should work:
1. Click in a field (for example Nom)
2. type a name (for example Roger Roger)
3. Hit Enter. My cursor goes into the next field. 
4. I keep doing this until the last field. When I hit enter in the last field, the Save button is selected and I can press Enter to save the contact.

Note: I can use tab and shift-tab to move between fields, which is great. But if I keep pressing tab I can move right out of the form, which is strange. Should the tab cycle through the fields and buttons within the form only?

**Comment by SuhailAliyar** [comment]
Assigning to @raseemayatt.

**Comment by raseemayatt** [comment]
@troughc allowed to move the next input field by clicking enter button in contact form

**Comment by troughc** [comment]
This works in the Amin panel Contact form.
It doesn't work well when you are creating an event and you click Contact and then click + Add new contact (when the dialog box pops up). 

Note: there is a bigger issue to discuss - how to manage 'contacts' in the system. And the link between a contact and an organizer as well the difference.  See issue FOR DISCUSSION: role of Contacts vs Organizers vs Performers - Footlight Admin #126
