### ISSUE TITLE
UI: Add Taxonomies - Event Type (additionalType in backend) and Audience

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#57]
Refer to slide 23 in the wireframes.  Try to make the spacing as compact as possible without crowding (keeps white space). For example, some of the field can appear in the column with the photo.
 
For the accessibility taxonomy, we haven't created sample data, but it will contain things related to the event such as "Sign language" and "Relaxed" and "Simultaneous translation".

![Image](https://user-images.githubusercontent.com/419491/175305352-05c2001e-4618-4a2f-bce9-2d5ea12bf756.png)

**Comment by saumier** [comment]
We will start with 2 taxonomies: Audience and Event Type as displayed in the current front-end calendar.  The Event Type should have a hierarchy so we can test the feature to include all events from a branch of the hierarchy.

**Comment by troughc** [comment]
PASS
