### ISSUE TITLE
Event detail page - Rachid

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#6]
Sample event series: "Rachid Badouri - Les fleurs du tapis" with no ticket offers.

<img width="1187" alt="Screen Shot 2022-05-12 at 8 45 27 AM" src="https://user-images.githubusercontent.com/419491/168077687-e024b38b-e218-4cde-9370-c9afcaa756cd.png">

# Components

### Dates component
<img width="382" alt="Screen Shot 2022-05-12 at 8 40 43 AM" src="https://user-images.githubusercontent.com/419491/168076836-538bc85d-a805-4274-80ec-467e826b8aeb.png">

### Location component
<img width="405" alt="Screen Shot 2022-05-12 at 8 39 53 AM" src="https://user-images.githubusercontent.com/419491/168076658-a1468414-c8a9-4c6a-a0e7-c21af6d52e4f.png">

### Types component
<img width="239" alt="Screen Shot 2022-05-12 at 8 44 47 AM" src="https://user-images.githubusercontent.com/419491/168077563-4fe52ce8-e2f0-4d13-9dff-1329727cc5ee.png">

### Social Media component
<img width="169" alt="Screen Shot 2022-05-12 at 8 41 32 AM" src="https://user-images.githubusercontent.com/419491/168077424-1b2a6329-f588-40d8-95e3-abb04c7236ed.png">

### Save component
<img width="229" alt="Screen Shot 2022-05-12 at 8 41 28 AM" src="https://user-images.githubusercontent.com/419491/168077446-65e84fc4-85c3-4f86-99c1-513cf4536664.png">

### Contact component
note: includes telephone, email and website. Added email to sample date, but not shown in image here.

<img width="392" alt="Screen Shot 2022-05-12 at 8 41 40 AM" src="https://user-images.githubusercontent.com/419491/168077372-e0443844-d507-47f8-aa38-e4ab189f647c.png">

### Audience component
<img width="391" alt="Screen Shot 2022-05-12 at 8 41 45 AM" src="https://user-images.githubusercontent.com/419491/168077341-51d63bd3-06c7-49e3-afb7-59d6df3384e0.png">

### Organizer component
<img width="391" alt="Screen Shot 2022-05-12 at 8 41 49 AM" src="https://user-images.githubusercontent.com/419491/168077471-90be5bab-8a14-453f-9bde-d4050589cf1e.png">

**Comment by SuhailAliyar** [comment]
@saumier  We need to add social media (Twitter and Facebook) links to the sample data to events. 
Can you please take a look into it?

cc @troughc

**Comment by saumier** [comment]
@SuhailAliyar @raseemayatt The social media icons are for sharing the event as per the current Caligram implementation.  For example, when you click Facebook the use is asked to write something like in this screen grab. Similar for Twitter

![Image](https://user-images.githubusercontent.com/419491/169917895-f9ce37a2-3bef-4a30-87b2-92882367d62d.png)
