### ISSUE TITLE
time not appearing when going from daily to custom

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-calendar-app#74]
Issue discovered when testing #113 in api repository.
Steps to reproduce (:
Create daily custom event 
Set date range 
Set start time 
Click Customize.
Times do not appear in Custom Recurring Event dialog

![Image](https://user-images.githubusercontent.com/64489312/178013995-2385df4a-84c7-45c6-bdf8-f1f5f7483b39.png)

**Comment by SuhailAliyar** [comment]
In this case, the daily custom event is not created(not saved) but the same config is used to migrate to custom dates. This logic is handled in  UI.
@raseemayatt can take a look into this.

**Comment by troughc** [comment]
Tested and PASSED using this event: http://footlight-calendar-frontend.herokuapp.com/events/caitlin-test-go-from-daily-with-times-to-custom-recurring/62d1b56f83d33300709a1cc2?lang=fr&date=2022-07-18_20-00-00
