### ISSUE TITLE
duplicate event created after saving

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-calendar-app#75]
I created an event named Caitlin Test 2 - Facebook valid URL

I am not sure but I  _think_ I clicked Save 2 times at the end (there was a delay in it saving). 
Two duplicate events were created:

<img width="1101" alt="Screen Shot 2022-07-08 at 11 19 40 AM" src="https://user-images.githubusercontent.com/64489312/178022935-3ed4513c-6be3-49e7-a53b-b9f1e0521000.png">
<img width="934" alt="Screen Shot 2022-07-08 at 11 22 10 AM" src="https://user-images.githubusercontent.com/64489312/178022952-fa6f69ca-ff83-49a1-ba4b-63871515b053.png">

I tried to reproduce this but could not. Can you tell what happened by looking at the event I created here?

**Comment by saumier** [comment]
Will address in UX redesign - buttons to become inactive when clicked.
