### ISSUE TITLE
Fix labels (spelling etc) for Lieu/Place UI

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-calendar-app#76]
Need to fix spelling of field names (labels) and order of fields for Place/Lieu in both French and English:
### French
**In left sidebar**
- change "Lieu" to "Lieus"
**In Lieu page**
- change "Lieu" to "Lieus"
- change "Toponymie" to "Nom de Lieu"
- change button "+ Add Lieu" to "+" _(global suggestion: we just us a + sign for all buttons that are for adding something)_
**In "Ajouter un Lieu" :
change breadcrumb label to Lieus > Ajouter un Lieu (is this correct @saumier ?)
Also, change spelling and order to the following spelling and order:**
Toponymie -----Nom
Adresse municipale ----Adresse de rue
Localité -----Municipalité
OUTAOUAIS -----Province
Code postal ------Code postal 
Pays --------Pays
Latitude
Longitude 
Description ------Déscription
Contenu en place

### English
In "Places" 
- change button from "+ Add Place" to "+"
- TO DISCUSS - should we change "Place Name" to "Name"? Same question for French
In "Add Place"
Change title "Places" to "Place" 
change spelling and order to the following spelling and order:**
Place Name ----- Name
Street Address
Locality ----- Municipality 
REGION ------ Province or Territory
Postal Code
Country
Latitude
Longitude
Description
Contained In Place

Please review @saumier before we add.

**Comment by saumier** [comment]
@troughc I did a full pass. I couldn't easily change the order of the fields. I used "province" for now without "territory".  Everything else should be updated.
