### ISSUE TITLE
press Enter behaviour

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-calendar-app#77]
In Footlight Admin - when I am in a field entering text, a URL, selecting from a dropdown etc, what happens when I press ENTER on the keyboard? 
- If required fields are not filled, they are highlighted to be filled. My cursor remains where it is.
- If all required fields are already filled, the event is either SAVED or UPDATED.

This is not the behaviour I want. I want the cursor to move to the next field so that I can continue working on the event.

An example of what I do not want: If an event has all required fields filled and I type a URL in the Facebook URL and then press ENTER, the event closes and is saved / updated.

**Comment by saumier** [comment]
Will address with UX redesign
