### ISSUE TITLE
Links to Facebook and Event Page, they are NOT displayed on event listing page.

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-calendar-app#78]
Steps to reproduce:
1. Create an event
2. Add a link to FB and/or the event page and then save
3. Go to listing site and look at that event
4. The FB and/or Event page URLs are not displayed.

**Comment by saumier** [comment]
Fixed. 

![Image](https://user-images.githubusercontent.com/419491/179301949-0c7ec22f-2c32-4d81-94a4-47aec807f845.png)
