### ISSUE TITLE
fix labels for times and more everywhere including in Custom Recurring Events dialog

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-calendar-app#81]
The labels for the start time and end time in the UI is wrong everywhere (see screenshots). Accents are also sometimes missing (for example Événement is sometimes missing accents)

In Custom Recurring Events dialog, the + Add Time label also needs attention
My suggestion:
Change "+ Add Time" to "+ Time" or "Add Time"
Then, after you click that...
Fix the first "Heure de finFin" field with label for start time and second "Heure de finFin" field for label for end time.

**Simple event (not recurring) needs labels to be fixed**
![Image](https://user-images.githubusercontent.com/64489312/179288291-44d47270-4ef1-4df1-af15-955b3d5c7d32.png)

**Daily and weekly recurring events need labels to be fixed**
![Image](https://user-images.githubusercontent.com/64489312/179288500-b18c9921-65a9-42ff-b231-8cb82cec01d2.png)

**Custom Recurring Events dialog needs labels to be fixed**
![Image](https://user-images.githubusercontent.com/64489312/179288356-c08cbf55-be5e-445b-9318-2dc45b655b3f.png)

**Comment by saumier** [comment]
Fixed all Heure de finFin and accents in Événement. Choice of "+ Add Time" will be decided in future wireframe.
