### ISSUE TITLE
Organization for "presented by"

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#88]
See UI in issue #87

**Comment by troughc** [comment]
tested and passed - organization looks and functions like wireframe provided by @saumier 
Added a new organization (friends of the moulin rouge)
Added a contact to the organization (Toulouse-Lautrec)
Added a new event with the organization available in the 'presented by' dropdown
NOTE: presenting organization does not get displayed on event details page yet. I assume that will be worked on later @saumier ?
Closing this issue and moving to Done
