### ISSUE TITLE
Event detail page - Scott

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#9]
Sample event: Fête champêtre chez les Scott

This event has ticket offers.

<img width="1156" alt="Screen Shot 2022-05-12 at 8 56 30 AM" src="https://user-images.githubusercontent.com/419491/168079708-3ca1ecb8-c846-4aea-8b26-5da09fc2f519.png">

## New components

Buy Button
<img width="380" alt="Screen Shot 2022-05-12 at 8 58 33 AM" src="https://user-images.githubusercontent.com/419491/168080121-a1c1fada-4ee0-45d3-aaba-b3605924d479.png">

Facebook Button
<img width="383" alt="Screen Shot 2022-05-12 at 8 58 38 AM" src="https://user-images.githubusercontent.com/419491/168080103-fb65739a-bc99-4000-89ee-04d6aadb7364.png">

Offer
<img width="390" alt="Screen Shot 2022-05-12 at 8 57 08 AM" src="https://user-images.githubusercontent.com/419491/168079820-51a00070-aa23-47d9-b883-030894d605bb.png">

**Comment by SuhailAliyar** [comment]
@saumier We don't capture the Facebook URL and the ticket buying URL in the sample data.  
Can you please look into it?

**Comment by saumier** [comment]
@SuhailAliyar I have added the Buy Button URL to the sample data in Airtable. The URL is https://www.eventbrite.ca/e/billets-fete-champetre-chez-les-scott-323503286037?fbclid=IwAR2rjn3l3LmlFYAXKrZqYu1rE0l39MERjRjVeIDCFRh3z0jK-12yIrMxjF8

**Comment by SuhailAliyar** [comment]
@saumier Thanks for adding the Buy URL.
Can you please add the Facebook URL too?

**Comment by SuhailAliyar** [comment]
Added support to persist facebook URLs with events from the sample data and to include Facebook URL along with the event-detail-API.

**Comment by SuhailAliyar** [comment]
Assigning back to @raseemayatt as the APIs are modified to have the buy URL and Facebook URL.

cc @saumier
