### ISSUE TITLE
Front-end: Back button

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#95]
In the front-end, when browsing events, I click on an event to see the event details, and then click the browser's back button so I can return to the list of events and look at the next events.  

Priority: 
1. page number
2. BONUS: window scroll.

## Expected behaviour
I expect to be able to click the back button and return to where I was in the search results so I can click on the next event in my list. If I have scrolled down the search results window, then I expect the back button to maintain the scroll position when I return. If I am on the second or third page of results, then I expect the back button to bring me back to the page of results that I was on. If I had selected the type Music, then I expect to still see only Music events.

Note: this is the current behaviour of ToutCulture https://toutculture.ca.

## Current behaviour
Currently the back button always brings me to the top of the first page of scroll results.  This makes it very difficult to browse the events because I have to remember which page I was on and scroll down the list to find the event I was just looking at so I can click on the next event.

Note: The URL on the search page should be updated to reflect the search criteria as well.

**Comment by saumier** [comment]
@raseemayatt  The browser back button does not behave as expected. On safari and Chrome, when I click on the back button, the window starts at the top and scrolls down.  On the current [Toutculture](https://toutculture.ca) site the browser back button just returns you to the previous page with the correct scroll.

**Comment by raseemayatt** [comment]
@saumier I have removed top to event scrolling. Can you please retest this issue

**Comment by saumier** [comment]
@raseemayatt Great. Now this behaves as I expect, and it behaves the same as the current toutculture.ca implementation. Thx.
