### ISSUE TITLE
Place holder image for events without an image

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-calendar-app#96]
Here is an image placeholder for events without an image. Please load into our image server.

![Image](https://user-images.githubusercontent.com/419491/181016204-0b540503-2c85-4c16-8e18-ba6b038eae99.png)

**Comment by saumier** [comment]
Here is an image placeholder for events without an image. Please load into our image server.

![Image](https://user-images.githubusercontent.com/419491/181016204-0b540503-2c85-4c16-8e18-ba6b038eae99.png)

**Comment by saumier** [comment]
Image needs to be updated in the event details page in the front-end.

**Comment by troughc** [comment]
PASS
